name: Push manager image 1.24.2

on:
  push:
    branches: [publish-docker-image-1.24.2]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-manager-image-1-24-2:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21 and Gradle cache
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Update version in package.json files
        id: update-package-json
        run: |
          VERSION=$(awk '{print tolower($0)}' <<< $VERSION)

          QUALIFIER=$(sed -E 's/.+-([a-z]+).*/\1/g' <<< $VERSION)
          if [ "$QUALIFIER" == "$VERSION" ]; then
            QUALIFIER=""
          fi

          if [ "$QUALIFIER" == "" ]; then
            TAG="latest"
          else
            if [ "$QUALIFIER" == "snapshot" ]; then
              # Add a timestamp to snapshot versions
              VERSION="$VERSION.$(date +'%Y%m%d%H%M%S')"
            else
              # Separate qualifiers from numbers of alpha, beta, rc versions
              VERSION=$(sed "s/$QUALIFIER/$QUALIFIER./g" <<< $VERSION)
            fi
            TAG="$QUALIFIER"
          fi

          find ui -maxdepth 3 -name package.json | xargs -I{} sed -i -E "s#\"version\": \".+\",#\"version\": \"$VERSION\",#" {}

          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          VERSION: 1.24.2

      - name: Run Install Dist
        timeout-minutes: 20
        run: ./gradlew installDist -x :deployment:installDist

      - name: Install QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: linux/amd64,linux/aarch64

      - name: Install Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Parse tags and evaluate conditions
        id: meta
        shell: bash
        run: |
          echo "formatted_tags=ekhorn/manager:c312ee8,ekhorn/manager:latest,ekhorn/manager:1.24.2" | tee -a $GITHUB_OUTPUT
          echo "first_tag=latest" | tee -a $GITHUB_OUTPUT
          echo "should_push=true" | tee -a $GITHUB_OUTPUT

      - name: Build and load manager image for Grype scan
        timeout-minutes: 20
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: manager/build/install/manager
          platforms: linux/amd64 # "ubuntu-latest" runs on x86 GitHub runners
          load: true # Load image locally for Grype Scan
          push: false
          tags: ${{ steps.meta.outputs.formatted_tags }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          cache-from: type=gha,scope=manager
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

      # - name: Scan manager docker image
      #   uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
      #   id: manager-anchore-scan
      #   with:
      #     image: ${{ steps.manager-docker-command.outputs.first_tag }}
      #     fail-build: true
      #     severity-cutoff: critical

      # - name: Upload Anchore scan SARIF report
      #   uses: github/codeql-action/upload-sarif@b8bb9f28b8d3f992092362369c57161b755dea45 # v4.35.0
      #   if: ${{ always() && steps.meta.outputs.should_push == 'true' }}
      #   with:
      #     sarif_file: ${{ steps.manager-anchore-scan.outputs.sarif }}

      # - name: Inspect Anchore scan SARIF report
      #   if: ${{ always() && steps.meta.outputs.should_push == 'true' }}
      #   run: cat ${{ steps.manager-anchore-scan.outputs.sarif }}

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        if: ${{ success() && steps.meta.outputs.should_push == 'true' }}
        with:
          username: ${{ secrets._TEMP_DOCKERHUB_USER }}
          password: ${{ secrets._TEMP_DOCKERHUB_PASSWORD }}

      - name: Build multi-platform manager image
        timeout-minutes: 20
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: manager/build/install/manager
          platforms: linux/amd64,linux/aarch64
          load: false
          push: ${{ steps.meta.outputs.should_push == 'true' }}
          tags: ${{ steps.meta.outputs.formatted_tags }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          cache-from: type=gha,scope=manager
          cache-to: type=gha,mode=max,scope=manager
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
